### ISSUE TITLE
【コンテンツ追加】 - header - menu

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GlassesPretty#6]
**関連情報**
#21

**ver0.0.0**
#7

**コンテンツ**
 - header

**TODO**
 - [x] menu項目を考える
 - [x] menu項目を作成 #22 
 - [x] menu項目のデザインを考える
 - [ ] menu項目をリンクする 
 - [ ] menu項目のcssにリンクする

**項目**
 - [ ] #8 HOME [HOME](http://sunstripe.main.jp/GlassesPretty/index.html)
 - [ ] #9 ランキング [Ranking](http://sunstripe.main.jp/GlassesPretty/ranking.html)
 - [ ] #10 一覧 [List](http://sunstripe.main.jp/GlassesPretty/list.html)
 - [ ] #11 ニュース [NEWS](http://sunstripe.main.jp/GlassesPretty/news.html)
 - [ ] #12 設定 [Settings](http://sunstripe.main.jp/GlassesPretty/settings.html)

**メニューデザイン**
- [x] menuButton 参考 https://www.nxworld.net/tips/css-only-button-design-and-hover-effects.html
